// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	User
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	JWTSignRequest
	JWTSignResponse
	JWTVerifyRequest
	JWTverifyResponse
	UpdateRequest
	ChangePwdRequest
	ChangePwdResponse
	UpdateResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Stdno    string `protobuf:"bytes,2,opt,name=stdno" json:"stdno,omitempty"`
	Realname string `protobuf:"bytes,3,opt,name=realname" json:"realname,omitempty"`
	Grade    string `protobuf:"bytes,4,opt,name=grade" json:"grade,omitempty"`
	College  string `protobuf:"bytes,5,opt,name=college" json:"college,omitempty"`
	Phone    string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	Qq       string `protobuf:"bytes,7,opt,name=qq" json:"qq,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetStdno() string {
	if m != nil {
		return m.Stdno
	}
	return ""
}

func (m *User) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *User) GetGrade() string {
	if m != nil {
		return m.Grade
	}
	return ""
}

func (m *User) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetQq() string {
	if m != nil {
		return m.Qq
	}
	return ""
}

type CreateRequest struct {
	Stdno    string `protobuf:"bytes,1,opt,name=stdno" json:"stdno,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Realname string `protobuf:"bytes,3,opt,name=realname" json:"realname,omitempty"`
	Grade    string `protobuf:"bytes,4,opt,name=grade" json:"grade,omitempty"`
	College  string `protobuf:"bytes,5,opt,name=college" json:"college,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetStdno() string {
	if m != nil {
		return m.Stdno
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateRequest) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *CreateRequest) GetGrade() string {
	if m != nil {
		return m.Grade
	}
	return ""
}

func (m *CreateRequest) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

type CreateResponse struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReadRequest struct {
	Stdno string `protobuf:"bytes,1,opt,name=stdno" json:"stdno,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetStdno() string {
	if m != nil {
		return m.Stdno
	}
	return ""
}

type ReadResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type JWTSignRequest struct {
	Stdno    string `protobuf:"bytes,1,opt,name=stdno" json:"stdno,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *JWTSignRequest) Reset()                    { *m = JWTSignRequest{} }
func (m *JWTSignRequest) String() string            { return proto.CompactTextString(m) }
func (*JWTSignRequest) ProtoMessage()               {}
func (*JWTSignRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *JWTSignRequest) GetStdno() string {
	if m != nil {
		return m.Stdno
	}
	return ""
}

func (m *JWTSignRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type JWTSignResponse struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *JWTSignResponse) Reset()                    { *m = JWTSignResponse{} }
func (m *JWTSignResponse) String() string            { return proto.CompactTextString(m) }
func (*JWTSignResponse) ProtoMessage()               {}
func (*JWTSignResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *JWTSignResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type JWTVerifyRequest struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *JWTVerifyRequest) Reset()                    { *m = JWTVerifyRequest{} }
func (m *JWTVerifyRequest) String() string            { return proto.CompactTextString(m) }
func (*JWTVerifyRequest) ProtoMessage()               {}
func (*JWTVerifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *JWTVerifyRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type JWTverifyResponse struct {
	Stdno string `protobuf:"bytes,1,opt,name=stdno" json:"stdno,omitempty"`
}

func (m *JWTverifyResponse) Reset()                    { *m = JWTverifyResponse{} }
func (m *JWTverifyResponse) String() string            { return proto.CompactTextString(m) }
func (*JWTverifyResponse) ProtoMessage()               {}
func (*JWTverifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *JWTverifyResponse) GetStdno() string {
	if m != nil {
		return m.Stdno
	}
	return ""
}

type UpdateRequest struct {
	Stdno string `protobuf:"bytes,1,opt,name=stdno" json:"stdno,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Qq    string `protobuf:"bytes,3,opt,name=qq" json:"qq,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateRequest) GetStdno() string {
	if m != nil {
		return m.Stdno
	}
	return ""
}

func (m *UpdateRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateRequest) GetQq() string {
	if m != nil {
		return m.Qq
	}
	return ""
}

type ChangePwdRequest struct {
	Stdno    string `protobuf:"bytes,1,opt,name=stdno" json:"stdno,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *ChangePwdRequest) Reset()                    { *m = ChangePwdRequest{} }
func (m *ChangePwdRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangePwdRequest) ProtoMessage()               {}
func (*ChangePwdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ChangePwdRequest) GetStdno() string {
	if m != nil {
		return m.Stdno
	}
	return ""
}

func (m *ChangePwdRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChangePwdResponse struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *ChangePwdResponse) Reset()                    { *m = ChangePwdResponse{} }
func (m *ChangePwdResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangePwdResponse) ProtoMessage()               {}
func (*ChangePwdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ChangePwdResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*JWTSignRequest)(nil), "JWTSignRequest")
	proto.RegisterType((*JWTSignResponse)(nil), "JWTSignResponse")
	proto.RegisterType((*JWTVerifyRequest)(nil), "JWTVerifyRequest")
	proto.RegisterType((*JWTverifyResponse)(nil), "JWTverifyResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*ChangePwdRequest)(nil), "ChangePwdRequest")
	proto.RegisterType((*ChangePwdResponse)(nil), "ChangePwdResponse")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	JWTSign(ctx context.Context, in *JWTSignRequest, opts ...client.CallOption) (*JWTSignResponse, error)
	JWTVerify(ctx context.Context, in *JWTVerifyRequest, opts ...client.CallOption) (*JWTverifyResponse, error)
	ChangePwd(ctx context.Context, in *ChangePwdRequest, opts ...client.CallOption) (*ChangePwdResponse, error)
}

type authClient struct {
	c           client.Client
	serviceName string
}

func NewAuthClient(serviceName string, c client.Client) AuthClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "auth"
	}
	return &authClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) JWTSign(ctx context.Context, in *JWTSignRequest, opts ...client.CallOption) (*JWTSignResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.JWTSign", in)
	out := new(JWTSignResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) JWTVerify(ctx context.Context, in *JWTVerifyRequest, opts ...client.CallOption) (*JWTverifyResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.JWTVerify", in)
	out := new(JWTverifyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChangePwd(ctx context.Context, in *ChangePwdRequest, opts ...client.CallOption) (*ChangePwdResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.ChangePwd", in)
	out := new(ChangePwdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	JWTSign(context.Context, *JWTSignRequest, *JWTSignResponse) error
	JWTVerify(context.Context, *JWTVerifyRequest, *JWTverifyResponse) error
	ChangePwd(context.Context, *ChangePwdRequest, *ChangePwdResponse) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Auth{hdlr}, opts...))
}

type Auth struct {
	AuthHandler
}

func (h *Auth) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.AuthHandler.Create(ctx, in, out)
}

func (h *Auth) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.AuthHandler.Read(ctx, in, out)
}

func (h *Auth) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.AuthHandler.Update(ctx, in, out)
}

func (h *Auth) JWTSign(ctx context.Context, in *JWTSignRequest, out *JWTSignResponse) error {
	return h.AuthHandler.JWTSign(ctx, in, out)
}

func (h *Auth) JWTVerify(ctx context.Context, in *JWTVerifyRequest, out *JWTverifyResponse) error {
	return h.AuthHandler.JWTVerify(ctx, in, out)
}

func (h *Auth) ChangePwd(ctx context.Context, in *ChangePwdRequest, out *ChangePwdResponse) error {
	return h.AuthHandler.ChangePwd(ctx, in, out)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x14, 0xb4, 0x5d, 0x27, 0xa1, 0xaf, 0x8d, 0x93, 0x3c, 0x71, 0x58, 0x7c, 0xaa, 0x16, 0x21, 0xb5,
	0x2a, 0xec, 0xa1, 0x20, 0xee, 0x50, 0x4e, 0xe1, 0x82, 0x4c, 0x4a, 0xce, 0x0b, 0xfb, 0x48, 0x22,
	0x82, 0xd7, 0xf6, 0x3a, 0x54, 0xfd, 0x08, 0x7e, 0x81, 0x0b, 0x3f, 0x8a, 0xbc, 0x6b, 0x9b, 0x38,
	0x29, 0x54, 0xaa, 0x7a, 0x9c, 0xf5, 0xec, 0xdb, 0x79, 0x33, 0x23, 0x03, 0xc8, 0x4d, 0xb9, 0x14,
	0x59, 0xa1, 0x4b, 0xcd, 0x7f, 0xf9, 0x10, 0x5e, 0x19, 0x2a, 0x30, 0x82, 0x60, 0xa5, 0x98, 0x7f,
	0xe2, 0x9f, 0xf6, 0x92, 0x60, 0xa5, 0xf0, 0x31, 0xf4, 0x4c, 0xa9, 0x52, 0xcd, 0x82, 0x13, 0xff,
	0xf4, 0x30, 0x71, 0x00, 0x63, 0x78, 0x54, 0x90, 0x5c, 0xa7, 0xf2, 0x3b, 0xb1, 0x03, 0xfb, 0xa1,
	0xc5, 0xd5, 0x8d, 0x45, 0x21, 0x15, 0xb1, 0xd0, 0xdd, 0xb0, 0x00, 0x19, 0x0c, 0xbe, 0xe8, 0xf5,
	0x9a, 0x16, 0xc4, 0x7a, 0xf6, 0xbc, 0x81, 0x15, 0x3f, 0x5b, 0xea, 0x94, 0x58, 0xdf, 0xf1, 0x2d,
	0xa8, 0x74, 0xe4, 0x39, 0x1b, 0xd8, 0xa3, 0x20, 0xcf, 0xf9, 0x4f, 0x1f, 0x86, 0x97, 0x05, 0xc9,
	0x92, 0x12, 0xca, 0x37, 0x64, 0xca, 0xbf, 0xca, 0xfc, 0x1d, 0x65, 0x99, 0x34, 0xe6, 0x5a, 0x17,
	0xaa, 0x96, 0xdc, 0xe2, 0x87, 0x54, 0xcd, 0x5f, 0x43, 0xd4, 0xc8, 0x31, 0x99, 0x4e, 0x0d, 0xdd,
	0xe6, 0x5c, 0xa9, 0xbf, 0x51, 0xda, 0x38, 0x67, 0x01, 0x7f, 0x0a, 0x47, 0x09, 0x49, 0xf5, 0xdf,
	0x25, 0xf8, 0x19, 0x1c, 0x3b, 0x52, 0x3d, 0xfa, 0x09, 0x84, 0x1b, 0x43, 0x85, 0x25, 0x1d, 0x5d,
	0xf4, 0x44, 0x95, 0x54, 0x62, 0x8f, 0xf8, 0x5b, 0x88, 0xa6, 0xf3, 0xd9, 0xc7, 0xd5, 0x22, 0xbd,
	0xb7, 0x2f, 0xfc, 0x1c, 0x46, 0xed, 0x8c, 0xfa, 0x45, 0x06, 0x83, 0x4c, 0xde, 0xac, 0xb5, 0x54,
	0xf5, 0x98, 0x06, 0xf2, 0xe7, 0x30, 0x9e, 0xce, 0x67, 0x9f, 0xa8, 0x58, 0x7d, 0xbd, 0x69, 0x9e,
	0xfc, 0x37, 0xfb, 0x0c, 0x26, 0xd3, 0xf9, 0xec, 0x47, 0xcd, 0xae, 0x87, 0xdf, 0xbe, 0xf4, 0x7b,
	0x18, 0x5e, 0x65, 0xea, 0xce, 0x80, 0xdb, 0xba, 0x04, 0xfb, 0x75, 0x39, 0x68, 0xeb, 0xf2, 0x0e,
	0xc6, 0x97, 0x4b, 0x99, 0x2e, 0xe8, 0xc3, 0xb5, 0xba, 0xbf, 0x31, 0x2f, 0x60, 0xb2, 0x35, 0xe5,
	0x4e, 0x6b, 0xc6, 0x10, 0x35, 0x1b, 0x38, 0xee, 0xc5, 0xef, 0x00, 0xc2, 0x37, 0x9b, 0x72, 0x89,
	0xe7, 0xd0, 0x77, 0x75, 0xc1, 0x48, 0x74, 0x6a, 0x1c, 0x8f, 0x44, 0xb7, 0x47, 0xdc, 0xc3, 0x67,
	0x10, 0x56, 0xf1, 0xe3, 0xb1, 0xd8, 0xaa, 0x4a, 0x3c, 0x14, 0xdb, 0x9d, 0xe0, 0x5e, 0x35, 0xd3,
	0x3d, 0x87, 0x91, 0xe8, 0x38, 0x17, 0x8f, 0x44, 0x57, 0x07, 0xf7, 0x50, 0xc0, 0xa0, 0xce, 0x18,
	0x47, 0xa2, 0xdb, 0x98, 0x78, 0x2c, 0x76, 0xe2, 0xe7, 0x1e, 0xbe, 0x82, 0xc3, 0x36, 0x66, 0x9c,
	0x88, 0xdd, 0xc8, 0x63, 0x14, 0x7b, 0xb9, 0xba, 0x5b, 0xad, 0x61, 0x38, 0x11, 0xbb, 0x11, 0xc4,
	0x28, 0xf6, 0xfc, 0xe4, 0xde, 0xe7, 0xbe, 0xfd, 0x07, 0xbd, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0xad, 0xea, 0x53, 0x91, 0x04, 0x00, 0x00,
}
